% TODO: load training dataset

% TODO: reshape and adjust the dimensions to be in the order of [height,width,1,sample_index]

layers = define_autoencoder();
% 'Momentum',0.9,...
options = trainingOptions('sgdm',...
                          'InitialLearnRate',1e-3,...
                          'LearnRateSchedule','piecewise',...
                          'LearnRateDropFactor',0.5,...
                          'LearnRateDropPeriod',2,...
                          'MaxEpochs',3,...
                          'MiniBatchSize',5,...
                          'Shuffle','every-epoch',...
                          'Plot','training-progress',...
                          'VerboseFrequency',20);
                  
% TODO: run trainNetwork()
load('../data/nist36_train.mat', 'train_data', 'train_labels');
X = zeros(32,32,1,size(train_data,1));
%Y = zeros(1,1,32,
for i=1:size(train_data,1)
    X(:,:,1,i) = reshape(train_data(i,:),32,32);
end
%T = reshape(train_data,1,32,32,10800);
net = trainNetwork(X,X,layers,options);

                      